Chatty.Web/Controllers/ChatRoomController.cs
using Chatty.Core.ChatRoom;
using Chatty.Core.User;
using Chatty.Web.Models;
using Chatty.Web.Models.ChatRoom;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Chatty.Web.Controllers
{
    [Authorize]
    public class ChatRoomController : Controller
    {
        private readonly IChatRoomManager chatRoomManager;
        private readonly IUserManager userManager;

        public ChatRoomController(IChatRoomManager chatRoomManager, IUserManager userManager)
        {
            this.chatRoomManager = chatRoomManager;
            this.userManager = userManager;
        }

        public async Task<ActionResult> Detail(string name)
        {
            await this.userManager.JoinRoomAsync();
            var messages = (await this.chatRoomManager.GetMessagesAsync(name))
                .Select(x => new MessageViewModel
                {
                    Message = x.Content,
                    UserId = x.UserId,
                    UserName = x.User.UserName,
                    Date = x.Date
                });

            return View(new ChatRoomDetailViewModel
            {
                Messages = messages,
                Name = name
            });
        }
    }
}

Chatty.Web/Controllers/HomeController.cs
using Chatty.Core.ChatRoom;
using Chatty.Core.User;
using Chatty.Database.Models;
using Chatty.Database.Repositories;
using Chatty.Web.Models.ChatRoom;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Chatty.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly IRepository<ChatRoom> chatRoomRepository;

        public HomeController(IRepository<ChatRoom> chatRoomRepository)
        {
            this.chatRoomRepository = chatRoomRepository;
        }

        public ActionResult Index()
        {
            var chatRooms = this.chatRoomRepository.All()
                .Select(x => new ChatRoomListItemViewModel
                {
                    Name = x.Name,
                    NumberOfUsers = x.Users.Count()
                });

            return View(chatRooms);
        }
    }
}

Chatty.Web/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Chatty.Web/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Chatty.Web/Views/Home/Index.cshtml
@model IEnumerable<Chatty.Web.Models.ChatRoom.ChatRoomListItemViewModel>
@{
    ViewBag.Title = "Home Page";
}

<div class="card">
    <div class="card-body">
        <h2 class="card-title">Chat Rooms</h2>
        <div class="card-text">
            <div class="table-responsive">
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th>
                                Name
                            </th>
                            <th>
                                Number of users
                            </th>
                            <th>
                                Options
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var room in Model)
                        {
                            <tr>
                                <td>
                                    @room.Name
                                </td>
                                <td>
                                    @room.NumberOfUsers
                                </td>
                                <td>
                                    <a href="@Url.Action("Detail", "ChatRoom", new { name = room.Name })" class="btn btn-xs btn-default waves-effect">
                                        <i class="material-icons">View</i>
                                    </a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>